### ISSUE TITLE
v 33.0.2 build is broken.

### ISSUE THREAD

**Issue by anandbn** [forcedotcom/dataloader#52]
I downloaded the latest from git and followed instructions and when I run the `mvn clean package -DskipTests` command I get the below compilation error:

```
[INFO] Compiling 157 source files to /Users/anarasimhan/dev/dataloader/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/anarasimhan/dev/dataloader/src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java:[256,28] cannot find symbol
symbol  : constructor CSVReader(java.io.FileInputStream,java.lang.String,char[])
location: class com.sforce.async.CSVReader
[ERROR] /Users/anarasimhan/dev/dataloader/src/main/java/com/salesforce/dataloader/dao/csv/CSVFileReader.java:[258,28] cannot find symbol
symbol  : constructor CSVReader(java.io.FileInputStream,char[])
location: class com.sforce.async.CSVReader
[INFO] 2 errors 
``` 
From what I could tell the v33.0.2 of force-wsc does'nt seem to have the latest code for that repo in it and the latest code is not reflected in the built JAR file.

**Comment by gnguyen-sfdc** [comment]
We are working on uploading a fixed version for 33.0.3, sorry for the inconvenience.

**Comment by anandbn** [comment]
Thanks. Had to compile it for a customer. For now I've made tweaks to a local copy of the CSVFileReader.java to resolve the compile issue and was able to get the JAR out.
